### ISSUE TITLE
view渲染考虑给一个高度，避免页面闪烁

### ISSUE THREAD

**Issue by xinglie** [thx/magix#7]
考虑这样的页面：

``` html
<div>
   <div mx-view="app/views/header"></div>
</div>
```

因渲染外层时，header并不占位置，当header内容渲染时，会导致整个页面内容向下推，从而引起页面闪烁

解决办法可以给header一个高度，对于无法确定高度的view，我们可以尝试给出一个合理的值，使得页面的闪烁不那么明显，同时渲染完成后移除这个高度。

考虑在magix内部解决该问题

**Comment by xinglie** [comment]
根据业务的不同，需求也不同，可以自己写一个类似
```css
[mx-view]{
  min-height:200px;
}
```
来自行解决
